[build]
  command = "pip install -r netlify/functions/requirements.txt"
  functions = "../netlify/functions"
  publish = "."
[functions]
  included_files = ["../templates/**", "../static/**"]
  node_bundler = "none"
  external_node_modules = []
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true
